### PR TITLE
bump version to 0.1.4

### PR DESCRIPTION
**Pull request by trevj**
I rebuilt the NPM so just wanted to update the version in package.json.

### CODE REVIEW

**Comment by ryscheng** [comment]
Just wondering why the sudden jump from 0.0.3 to 0.1.4?

**Comment by trevj** [comment]
i don't know! I discovered a pretty big mis-match between the NPM and package.json version number (0.1.3 vs. 0.0.3, respectively) and figured it was safer to just keep them all increasing.

**Comment by ryscheng** [comment]
Not sure what you mean exactly, but sure no biggie.
We should be using peerDependencies to understand which dependencies are
related between repos.
http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by iislucas** [comment]
Also let's try and use semantic versioning http://semver.org/; that helps
with version management in package files.

On Fri, Mar 28, 2014 at 3:24 PM, Raymond Cheng notifications@github.comwrote:

> Not sure what you mean exactly, but sure no biggie.
> We should be using peerDependencies to understand which dependencies are
> related between repos.
> http://blog.nodejs.org/2013/02/07/peer-dependencies/
> 
> On Fri, Mar 28, 2014 at 12:00 PM, yangoon notifications@github.com
> wrote:
> 
> > i don't know! I discovered a pretty big mis-match between the NPM and
> > package.json version number (0.1.3 vs. 0.0.3, respectively) and figured
> > it
> > was safer to just keep them all increasing.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/freedomjs/freedom-typescript-api/pull/6#issuecomment-38956091>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/freedomjs/freedom-typescript-api/pull/6#issuecomment-38958490
> .

## 

Lucas Dixon | Google Ideas

**Pull request merged**
