### PR TITLE
Add secure method to tcp socket typescript interface

### PR DESCRIPTION
**Pull request by dborkan**
Add secure method to tcp socket typescript interface

### CODE REVIEW

**Comment by dborkan** [comment]
FYI, this pull request is also related to https://github.com/freedomjs/freedom-for-firefox/pull/12 (firefox implementation) and https://github.com/freedomjs/freedom/pull/92 (freedom interface)

**Comment by iislucas** [comment]
This wants to be pulled in from uproxy-lib now; you want to move this patch to their?

**Comment by dborkan** [comment]
I just created https://github.com/uProxy/uproxy-lib/pull/42 for uproxy-lib.  It seems like this change should go in both places.  Also is there any reason why uproxy-lib needs its own copy of tcp-socket.d.ts?  It seems like this is going to remain identical between the 2 repos, and that uproxy-lib should only have freedom typescript interface files for providers where uproxy has changed the interface from what's in freedom (e.g. peerconnection)

**Comment by dborkan** [comment]
Just discussed this with Lucas, closing this request, we'll eventually merge changes back from uproxy-lib to this lib

**Pull request closed without merging**
